# generated : 2019-12-29:15:47  // template : ./setup/template/Makefile.jinja2

CURRENT_UID:=$(shell echo $$(id -u):$$(id -g))
export CURRENT_UID

down:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose down

clean:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose rm -f -v


taginfo-eu-ad:
	# make GDNAME=europe taginfo-eu-ad
	@echo " Start test  eu-ad :: Andorra     ::     mapped local port after finishing   127.0.0.1:20001"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-ad	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-ad /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-ad

taginfo-eu-al:
	# make GDNAME=europe taginfo-eu-al
	@echo " Start test  eu-al :: Albania     ::     mapped local port after finishing   127.0.0.1:20002"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-al	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-al /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-al

taginfo-eu-at:
	# make GDNAME=europe taginfo-eu-at
	@echo " Start test  eu-at :: Austria     ::     mapped local port after finishing   127.0.0.1:20003"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-at	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-at /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-at

taginfo-eu-ax:
	# make GDNAME=finland taginfo-eu-ax
	@echo " Start test  eu-ax :: Åland Islands     ::     mapped local port after finishing   127.0.0.1:20004"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-ax	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-ax /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-ax

taginfo-eu-ba:
	# make GDNAME=europe taginfo-eu-ba
	@echo " Start test  eu-ba :: Bosnia and Herzegovina     ::     mapped local port after finishing   127.0.0.1:20005"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-ba	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-ba /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-ba

taginfo-eu-be:
	# make GDNAME=europe taginfo-eu-be
	@echo " Start test  eu-be :: Belgium     ::     mapped local port after finishing   127.0.0.1:20006"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-be	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-be /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-be

taginfo-eu-bg:
	# make GDNAME=europe taginfo-eu-bg
	@echo " Start test  eu-bg :: Bulgaria     ::     mapped local port after finishing   127.0.0.1:20007"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-bg	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-bg /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-bg

taginfo-eu-by:
	# make GDNAME=belarus taginfo-eu-by
	@echo " Start test  eu-by :: Belarus     ::     mapped local port after finishing   127.0.0.1:20008"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-by	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-by /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-by

taginfo-eu-ch:
	# make GDNAME=europe taginfo-eu-ch
	@echo " Start test  eu-ch :: Switzerland     ::     mapped local port after finishing   127.0.0.1:20009"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-ch	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-ch /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-ch

taginfo-eu-cy:
	# make GDNAME=cyprus taginfo-eu-cy
	@echo " Start test  eu-cy :: Cyprus     ::     mapped local port after finishing   127.0.0.1:20010"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-cy	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-cy /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-cy

taginfo-eu-cz:
	# make GDNAME=czech-republic taginfo-eu-cz
	@echo " Start test  eu-cz :: Czechia     ::     mapped local port after finishing   127.0.0.1:20011"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-cz	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-cz /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-cz

taginfo-eu-de:
	# make GDNAME=europe taginfo-eu-de
	@echo " Start test  eu-de :: Germany     ::     mapped local port after finishing   127.0.0.1:20012"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-de	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-de /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-de

taginfo-eu-dk:
	# make GDNAME=europe taginfo-eu-dk
	@echo " Start test  eu-dk :: Denmark     ::     mapped local port after finishing   127.0.0.1:20013"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-dk	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-dk /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-dk

taginfo-eu-ee:
	# make GDNAME=europe taginfo-eu-ee
	@echo " Start test  eu-ee :: Estonia     ::     mapped local port after finishing   127.0.0.1:20014"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-ee	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-ee /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-ee

taginfo-eu-es:
	# make GDNAME=europe taginfo-eu-es
	@echo " Start test  eu-es :: Spain (except CanaryIsland)     ::     mapped local port after finishing   127.0.0.1:20015"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-es	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-es /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-es

taginfo-eu-fi:
	# make GDNAME=europe taginfo-eu-fi
	@echo " Start test  eu-fi :: Finland     ::     mapped local port after finishing   127.0.0.1:20016"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-fi	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-fi /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-fi

taginfo-eu-fo:
	# make GDNAME=europe taginfo-eu-fo
	@echo " Start test  eu-fo :: Faroe Islands     ::     mapped local port after finishing   127.0.0.1:20017"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-fo	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-fo /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-fo

taginfo-eu-fr-metropolitan:
	# make GDNAME=europe taginfo-eu-fr-metropolitan
	@echo " Start test  eu-fr-metropolitan :: Metropolitan France     ::     mapped local port after finishing   127.0.0.1:20018"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-fr-metropolitan	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-fr-metropolitan /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-fr-metropolitan

taginfo-eu-gb:
	# make GDNAME=europe taginfo-eu-gb
	@echo " Start test  eu-gb :: United Kingdom     ::     mapped local port after finishing   127.0.0.1:20019"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-gb	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-gb /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-gb

taginfo-eu-ge:
	# make GDNAME=europe taginfo-eu-ge
	@echo " Start test  eu-ge :: Georgia     ::     mapped local port after finishing   127.0.0.1:20020"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-ge	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-ge /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-ge

taginfo-eu-gg:
	# make GDNAME=france taginfo-eu-gg
	@echo " Start test  eu-gg :: Guernsey     ::     mapped local port after finishing   127.0.0.1:20021"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-gg	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-gg /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-gg

taginfo-eu-gi:
	# make GDNAME=spain taginfo-eu-gi
	@echo " Start test  eu-gi :: Gibraltar     ::     mapped local port after finishing   127.0.0.1:20022"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-gi	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-gi /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-gi

taginfo-eu-gr:
	# make GDNAME=europe taginfo-eu-gr
	@echo " Start test  eu-gr :: Greece     ::     mapped local port after finishing   127.0.0.1:20023"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-gr	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-gr /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-gr

taginfo-eu-hr:
	# make GDNAME=europe taginfo-eu-hr
	@echo " Start test  eu-hr :: Croatia     ::     mapped local port after finishing   127.0.0.1:20024"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-hr	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-hr /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-hr

taginfo-eu-hu:
	# make GDNAME=europe taginfo-eu-hu
	@echo " Start test  eu-hu :: Hungary     ::     mapped local port after finishing   127.0.0.1:20025"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-hu	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-hu /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-hu

taginfo-eu-ie:
	# make GDNAME=ireland-and-northern-ireland taginfo-eu-ie
	@echo " Start test  eu-ie :: Ireland     ::     mapped local port after finishing   127.0.0.1:20026"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-ie	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-ie /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-ie

taginfo-eu-im:
	# make GDNAME=isle-of-man taginfo-eu-im
	@echo " Start test  eu-im :: Isle of Man     ::     mapped local port after finishing   127.0.0.1:20027"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-im	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-im /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-im

taginfo-eu-is:
	# make GDNAME=iceland taginfo-eu-is
	@echo " Start test  eu-is :: Iceland     ::     mapped local port after finishing   127.0.0.1:20028"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-is	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-is /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-is

taginfo-eu-it:
	# make GDNAME=europe taginfo-eu-it
	@echo " Start test  eu-it :: Italy     ::     mapped local port after finishing   127.0.0.1:20029"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-it	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-it /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-it

taginfo-eu-je:
	# make GDNAME=france taginfo-eu-je
	@echo " Start test  eu-je :: Jersey     ::     mapped local port after finishing   127.0.0.1:20030"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-je	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-je /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-je

taginfo-eu-li:
	# make GDNAME=europe taginfo-eu-li
	@echo " Start test  eu-li :: Liechtenstein     ::     mapped local port after finishing   127.0.0.1:20031"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-li	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-li /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-li

taginfo-eu-lt:
	# make GDNAME=europe taginfo-eu-lt
	@echo " Start test  eu-lt :: Lithuania     ::     mapped local port after finishing   127.0.0.1:20032"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-lt	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-lt /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-lt

taginfo-eu-lu:
	# make GDNAME=europe taginfo-eu-lu
	@echo " Start test  eu-lu :: Luxembourg     ::     mapped local port after finishing   127.0.0.1:20033"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-lu	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-lu /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-lu

taginfo-eu-lv:
	# make GDNAME=europe taginfo-eu-lv
	@echo " Start test  eu-lv :: Latvia     ::     mapped local port after finishing   127.0.0.1:20034"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-lv	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-lv /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-lv

taginfo-eu-mc:
	# make GDNAME=provence-alpes-cote-d-azur taginfo-eu-mc
	@echo " Start test  eu-mc :: Monaco     ::     mapped local port after finishing   127.0.0.1:20035"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-mc	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-mc /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-mc

taginfo-eu-md:
	# make GDNAME=europe taginfo-eu-md
	@echo " Start test  eu-md :: Moldova     ::     mapped local port after finishing   127.0.0.1:20036"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-md	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-md /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-md

taginfo-eu-me:
	# make GDNAME=europe taginfo-eu-me
	@echo " Start test  eu-me :: Montenegro     ::     mapped local port after finishing   127.0.0.1:20037"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-me	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-me /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-me

taginfo-eu-mk:
	# make GDNAME=macedonia taginfo-eu-mk
	@echo " Start test  eu-mk :: North Macedonia     ::     mapped local port after finishing   127.0.0.1:20038"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-mk	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-mk /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-mk

taginfo-eu-mt:
	# make GDNAME=europe taginfo-eu-mt
	@echo " Start test  eu-mt :: Malta     ::     mapped local port after finishing   127.0.0.1:20039"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-mt	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-mt /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-mt

taginfo-eu-nl:
	# make GDNAME=europe taginfo-eu-nl
	@echo " Start test  eu-nl :: Netherlands(Eu)     ::     mapped local port after finishing   127.0.0.1:20040"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-nl	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-nl /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-nl

taginfo-eu-no:
	# make GDNAME=europe taginfo-eu-no
	@echo " Start test  eu-no :: Norway     ::     mapped local port after finishing   127.0.0.1:20041"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-no	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-no /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-no

taginfo-eu-pl:
	# make GDNAME=europe taginfo-eu-pl
	@echo " Start test  eu-pl :: Poland     ::     mapped local port after finishing   127.0.0.1:20042"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-pl	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-pl /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-pl

taginfo-eu-pt:
	# make GDNAME=europe taginfo-eu-pt
	@echo " Start test  eu-pt :: Portugal     ::     mapped local port after finishing   127.0.0.1:20043"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-pt	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-pt /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-pt

taginfo-eu-ro:
	# make GDNAME=romania taginfo-eu-ro
	@echo " Start test  eu-ro :: Romania     ::     mapped local port after finishing   127.0.0.1:20044"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-ro	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-ro /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-ro

taginfo-eu-rs:
	# make GDNAME=europe taginfo-eu-rs
	@echo " Start test  eu-rs :: Serbia     ::     mapped local port after finishing   127.0.0.1:20045"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-rs	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-rs /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-rs

taginfo-eu-se:
	# make GDNAME=europe taginfo-eu-se
	@echo " Start test  eu-se :: Sweden     ::     mapped local port after finishing   127.0.0.1:20046"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-se	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-se /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-se

taginfo-eu-si:
	# make GDNAME=europe taginfo-eu-si
	@echo " Start test  eu-si :: Slovenia     ::     mapped local port after finishing   127.0.0.1:20047"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-si	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-si /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-si

taginfo-eu-sk:
	# make GDNAME=europe taginfo-eu-sk
	@echo " Start test  eu-sk :: Slovakia     ::     mapped local port after finishing   127.0.0.1:20048"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-sk	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-sk /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-sk

taginfo-eu-sm:
	# make GDNAME=italy taginfo-eu-sm
	@echo " Start test  eu-sm :: San Marino     ::     mapped local port after finishing   127.0.0.1:20049"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-sm	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-sm /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-sm

taginfo-eu-tr:
	# make GDNAME=europe taginfo-eu-tr
	@echo " Start test  eu-tr :: Turkey     ::     mapped local port after finishing   127.0.0.1:20050"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-tr	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-tr /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-tr

taginfo-eu-ua:
	# make GDNAME=ukraine taginfo-eu-ua
	@echo " Start test  eu-ua :: Ukraine     ::     mapped local port after finishing   127.0.0.1:20051"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-ua	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-ua /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-ua

taginfo-eu-uk-sba:
	# make GDNAME=cyprus taginfo-eu-uk-sba
	@echo " Start test  eu-uk-sba :: British Sovereign Base Areas     ::     mapped local port after finishing   127.0.0.1:20052"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-uk-sba	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-uk-sba /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-uk-sba

taginfo-eu-va:
	# make GDNAME=centro taginfo-eu-va
	@echo " Start test  eu-va :: Vatican City     ::     mapped local port after finishing   127.0.0.1:20053"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-va	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-va /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-va

taginfo-eu-xk:
	# make GDNAME=europe taginfo-eu-xk
	@echo " Start test  eu-xk :: Kosovo     ::     mapped local port after finishing   127.0.0.1:20054"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-eu-xk	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-eu-xk /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-eu-xk


# generated : 2019-12-29:15:47