# generated : {{utcnow}}  // template : ./setup/template/Makefile.jinja2

down:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose down

clean:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose rm -f -v

{% for item in items %}
taginfo-{{continent}}-{{item.iso}}:
	@echo " Start test  {{continent}}-{{item.iso}} :: {{item.name_en}}     ::     mapped local port after finishing   127.0.0.1:{{item.port_order}}"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-{{continent}}-{{item.iso}} /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-{{continent}}-{{item.iso}}
{% endfor %}

# generated : {{utcnow}}
