# generated : 2019-12-29:15:08  // template : ./setup/template/Makefile.jinja2

CURRENT_UID:=$(shell echo $$(id -u):$$(id -g))
export CURRENT_UID

down:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose down

clean:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose rm -f -v


taginfo-af-ao:
	# make GDNAME=angola taginfo-af-ao
	@echo " Start test  af-ao :: Angola     ::     mapped local port after finishing   127.0.0.1:11001"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-ao	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-ao /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-ao

taginfo-af-bf:
	# make GDNAME=africa taginfo-af-bf
	@echo " Start test  af-bf :: Burkina Faso     ::     mapped local port after finishing   127.0.0.1:11002"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-bf	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-bf /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-bf

taginfo-af-bi:
	# make GDNAME=africa taginfo-af-bi
	@echo " Start test  af-bi :: Burundi     ::     mapped local port after finishing   127.0.0.1:11003"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-bi	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-bi /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-bi

taginfo-af-bj:
	# make GDNAME=benin taginfo-af-bj
	@echo " Start test  af-bj :: Benin     ::     mapped local port after finishing   127.0.0.1:11004"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-bj	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-bj /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-bj

taginfo-af-bv:
	# make GDNAME=africa taginfo-af-bv
	@echo " Start test  af-bv :: Bouvet Island     ::     mapped local port after finishing   127.0.0.1:11005"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-bv	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-bv /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-bv

taginfo-af-bw:
	# make GDNAME=africa taginfo-af-bw
	@echo " Start test  af-bw :: Botswana     ::     mapped local port after finishing   127.0.0.1:11006"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-bw	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-bw /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-bw

taginfo-af-cd:
	# make GDNAME=africa taginfo-af-cd
	@echo " Start test  af-cd :: Democratic Republic of the Congo     ::     mapped local port after finishing   127.0.0.1:11007"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-cd	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-cd /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-cd

taginfo-af-cf:
	# make GDNAME=central-african-republic taginfo-af-cf
	@echo " Start test  af-cf :: Central African Republic     ::     mapped local port after finishing   127.0.0.1:11008"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-cf	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-cf /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-cf

taginfo-af-cg:
	# make GDNAME=africa taginfo-af-cg
	@echo " Start test  af-cg :: Congo-Brazzaville     ::     mapped local port after finishing   127.0.0.1:11009"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-cg	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-cg /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-cg

taginfo-af-ci:
	# make GDNAME=africa taginfo-af-ci
	@echo " Start test  af-ci :: Côte d'Ivoire     ::     mapped local port after finishing   127.0.0.1:11010"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-ci	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-ci /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-ci

taginfo-af-cm:
	# make GDNAME=africa taginfo-af-cm
	@echo " Start test  af-cm :: Cameroon     ::     mapped local port after finishing   127.0.0.1:11011"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-cm	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-cm /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-cm

taginfo-af-cv:
	# make GDNAME=cape-verde taginfo-af-cv
	@echo " Start test  af-cv :: Cape Verde     ::     mapped local port after finishing   127.0.0.1:11012"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-cv	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-cv /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-cv

taginfo-af-dj:
	# make GDNAME=djibouti taginfo-af-dj
	@echo " Start test  af-dj :: Djibouti     ::     mapped local port after finishing   127.0.0.1:11013"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-dj	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-dj /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-dj

taginfo-af-dz:
	# make GDNAME=africa taginfo-af-dz
	@echo " Start test  af-dz :: Algeria     ::     mapped local port after finishing   127.0.0.1:11014"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-dz	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-dz /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-dz

taginfo-af-eg:
	# make GDNAME=africa taginfo-af-eg
	@echo " Start test  af-eg :: Egypt     ::     mapped local port after finishing   127.0.0.1:11015"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-eg	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-eg /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-eg

taginfo-af-er:
	# make GDNAME=eritrea taginfo-af-er
	@echo " Start test  af-er :: Eritrea     ::     mapped local port after finishing   127.0.0.1:11016"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-er	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-er /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-er

taginfo-af-es-ce:
	# make GDNAME=spain taginfo-af-es-ce
	@echo " Start test  af-es-ce :: Ceuta     ::     mapped local port after finishing   127.0.0.1:11017"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-es-ce	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-es-ce /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-es-ce

taginfo-af-es-cn:
	# make GDNAME=canary-islands taginfo-af-es-cn
	@echo " Start test  af-es-cn :: Canary Islands     ::     mapped local port after finishing   127.0.0.1:11018"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-es-cn	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-es-cn /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-es-cn

taginfo-af-es-gc:
	# make GDNAME=canary-islands taginfo-af-es-gc
	@echo " Start test  af-es-gc :: Las Palmas     ::     mapped local port after finishing   127.0.0.1:11019"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-es-gc	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-es-gc /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-es-gc

taginfo-af-es-ml:
	# make GDNAME=spain taginfo-af-es-ml
	@echo " Start test  af-es-ml :: Melilla     ::     mapped local port after finishing   127.0.0.1:11020"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-es-ml	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-es-ml /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-es-ml

taginfo-af-es-tf:
	# make GDNAME=canary-islands taginfo-af-es-tf
	@echo " Start test  af-es-tf :: Santa Cruz de Tenerife     ::     mapped local port after finishing   127.0.0.1:11021"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-es-tf	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-es-tf /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-es-tf

taginfo-af-et:
	# make GDNAME=africa taginfo-af-et
	@echo " Start test  af-et :: Ethiopia     ::     mapped local port after finishing   127.0.0.1:11022"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-et	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-et /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-et

taginfo-af-fr-may:
	# make GDNAME=mayotte taginfo-af-fr-may
	@echo " Start test  af-fr-may :: Mayotte     ::     mapped local port after finishing   127.0.0.1:11023"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-fr-may	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-fr-may /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-fr-may

taginfo-af-fr-yt:
	# make GDNAME=mayotte taginfo-af-fr-yt
	@echo " Start test  af-fr-yt :: Mayotte     ::     mapped local port after finishing   127.0.0.1:11024"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-fr-yt	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-fr-yt /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-fr-yt

taginfo-af-ga:
	# make GDNAME=gabon taginfo-af-ga
	@echo " Start test  af-ga :: Gabon     ::     mapped local port after finishing   127.0.0.1:11025"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-ga	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-ga /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-ga

taginfo-af-gh:
	# make GDNAME=africa taginfo-af-gh
	@echo " Start test  af-gh :: Ghana     ::     mapped local port after finishing   127.0.0.1:11026"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-gh	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-gh /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-gh

taginfo-af-gm:
	# make GDNAME=senegal-and-gambia taginfo-af-gm
	@echo " Start test  af-gm :: The Gambia     ::     mapped local port after finishing   127.0.0.1:11027"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-gm	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-gm /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-gm

taginfo-af-gn:
	# make GDNAME=africa taginfo-af-gn
	@echo " Start test  af-gn :: Guinea     ::     mapped local port after finishing   127.0.0.1:11028"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-gn	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-gn /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-gn

taginfo-af-gq:
	# make GDNAME=africa taginfo-af-gq
	@echo " Start test  af-gq :: Equatorial Guinea     ::     mapped local port after finishing   127.0.0.1:11029"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-gq	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-gq /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-gq

taginfo-af-gw:
	# make GDNAME=africa taginfo-af-gw
	@echo " Start test  af-gw :: Guinea-Bissau     ::     mapped local port after finishing   127.0.0.1:11030"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-gw	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-gw /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-gw

taginfo-af-ke:
	# make GDNAME=africa taginfo-af-ke
	@echo " Start test  af-ke :: Kenya     ::     mapped local port after finishing   127.0.0.1:11031"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-ke	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-ke /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-ke

taginfo-af-km:
	# make GDNAME=comores taginfo-af-km
	@echo " Start test  af-km :: Comoros     ::     mapped local port after finishing   127.0.0.1:11032"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-km	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-km /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-km

taginfo-af-lr:
	# make GDNAME=liberia taginfo-af-lr
	@echo " Start test  af-lr :: Liberia     ::     mapped local port after finishing   127.0.0.1:11033"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-lr	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-lr /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-lr

taginfo-af-ls:
	# make GDNAME=africa taginfo-af-ls
	@echo " Start test  af-ls :: Lesotho     ::     mapped local port after finishing   127.0.0.1:11034"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-ls	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-ls /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-ls

taginfo-af-ly:
	# make GDNAME=africa taginfo-af-ly
	@echo " Start test  af-ly :: Libya     ::     mapped local port after finishing   127.0.0.1:11035"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-ly	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-ly /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-ly

taginfo-af-ma:
	# make GDNAME=africa taginfo-af-ma
	@echo " Start test  af-ma :: Morocco     ::     mapped local port after finishing   127.0.0.1:11036"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-ma	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-ma /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-ma

taginfo-af-mg:
	# make GDNAME=africa taginfo-af-mg
	@echo " Start test  af-mg :: Madagascar     ::     mapped local port after finishing   127.0.0.1:11037"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-mg	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-mg /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-mg

taginfo-af-ml:
	# make GDNAME=mali taginfo-af-ml
	@echo " Start test  af-ml :: Mali     ::     mapped local port after finishing   127.0.0.1:11038"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-ml	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-ml /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-ml

taginfo-af-mr:
	# make GDNAME=africa taginfo-af-mr
	@echo " Start test  af-mr :: Mauritania     ::     mapped local port after finishing   127.0.0.1:11039"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-mr	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-mr /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-mr

taginfo-af-mu:
	# make GDNAME=mauritius taginfo-af-mu
	@echo " Start test  af-mu :: Mauritius     ::     mapped local port after finishing   127.0.0.1:11040"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-mu	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-mu /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-mu

taginfo-af-mw:
	# make GDNAME=africa taginfo-af-mw
	@echo " Start test  af-mw :: Malawi     ::     mapped local port after finishing   127.0.0.1:11041"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-mw	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-mw /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-mw

taginfo-af-mz:
	# make GDNAME=africa taginfo-af-mz
	@echo " Start test  af-mz :: Mozambique     ::     mapped local port after finishing   127.0.0.1:11042"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-mz	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-mz /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-mz

taginfo-af-na:
	# make GDNAME=namibia taginfo-af-na
	@echo " Start test  af-na :: Namibia     ::     mapped local port after finishing   127.0.0.1:11043"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-na	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-na /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-na

taginfo-af-ne:
	# make GDNAME=africa taginfo-af-ne
	@echo " Start test  af-ne :: Niger     ::     mapped local port after finishing   127.0.0.1:11044"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-ne	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-ne /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-ne

taginfo-af-ng:
	# make GDNAME=africa taginfo-af-ng
	@echo " Start test  af-ng :: Nigeria     ::     mapped local port after finishing   127.0.0.1:11045"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-ng	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-ng /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-ng

taginfo-af-re:
	# make GDNAME=reunion taginfo-af-re
	@echo " Start test  af-re :: Réunion     ::     mapped local port after finishing   127.0.0.1:11046"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-re	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-re /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-re

taginfo-af-rw:
	# make GDNAME=rwanda taginfo-af-rw
	@echo " Start test  af-rw :: Rwanda     ::     mapped local port after finishing   127.0.0.1:11047"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-rw	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-rw /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-rw

taginfo-af-sc:
	# make GDNAME=seychelles taginfo-af-sc
	@echo " Start test  af-sc :: Seychelles     ::     mapped local port after finishing   127.0.0.1:11048"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-sc	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-sc /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-sc

taginfo-af-sd:
	# make GDNAME=sudan taginfo-af-sd
	@echo " Start test  af-sd :: Sudan     ::     mapped local port after finishing   127.0.0.1:11049"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-sd	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-sd /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-sd

taginfo-af-sh:
	# make GDNAME=saint-helena-ascension-and-tristan-da-cunha taginfo-af-sh
	@echo " Start test  af-sh :: Saint Helena, Ascension and Tristan da Cunha     ::     mapped local port after finishing   127.0.0.1:11050"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-sh	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-sh /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-sh

taginfo-af-sl:
	# make GDNAME=africa taginfo-af-sl
	@echo " Start test  af-sl :: Sierra Leone     ::     mapped local port after finishing   127.0.0.1:11051"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-sl	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-sl /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-sl

taginfo-af-sn:
	# make GDNAME=africa taginfo-af-sn
	@echo " Start test  af-sn :: Senegal     ::     mapped local port after finishing   127.0.0.1:11052"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-sn	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-sn /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-sn

taginfo-af-so:
	# make GDNAME=somalia taginfo-af-so
	@echo " Start test  af-so :: Somalia     ::     mapped local port after finishing   127.0.0.1:11053"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-so	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-so /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-so

taginfo-af-ss:
	# make GDNAME=africa taginfo-af-ss
	@echo " Start test  af-ss :: South Sudan     ::     mapped local port after finishing   127.0.0.1:11054"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-ss	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-ss /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-ss

taginfo-af-st:
	# make GDNAME=sao-tome-and-principe taginfo-af-st
	@echo " Start test  af-st :: São Tomé and Príncipe     ::     mapped local port after finishing   127.0.0.1:11055"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-st	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-st /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-st

taginfo-af-sz:
	# make GDNAME=swaziland taginfo-af-sz
	@echo " Start test  af-sz :: Eswatini     ::     mapped local port after finishing   127.0.0.1:11056"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-sz	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-sz /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-sz

taginfo-af-td:
	# make GDNAME=chad taginfo-af-td
	@echo " Start test  af-td :: Chad     ::     mapped local port after finishing   127.0.0.1:11057"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-td	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-td /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-td

taginfo-af-tg:
	# make GDNAME=africa taginfo-af-tg
	@echo " Start test  af-tg :: Togo     ::     mapped local port after finishing   127.0.0.1:11058"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-tg	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-tg /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-tg

taginfo-af-tn:
	# make GDNAME=africa taginfo-af-tn
	@echo " Start test  af-tn :: Tunisia     ::     mapped local port after finishing   127.0.0.1:11059"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-tn	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-tn /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-tn

taginfo-af-tz:
	# make GDNAME=africa taginfo-af-tz
	@echo " Start test  af-tz :: Tanzania     ::     mapped local port after finishing   127.0.0.1:11060"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-tz	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-tz /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-tz

taginfo-af-ug:
	# make GDNAME=africa taginfo-af-ug
	@echo " Start test  af-ug :: Uganda     ::     mapped local port after finishing   127.0.0.1:11061"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-ug	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-ug /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-ug

taginfo-af-yt:
	# make GDNAME=africa taginfo-af-yt
	@echo " Start test  af-yt :: Mayotte     ::     mapped local port after finishing   127.0.0.1:11062"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-yt	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-yt /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-yt

taginfo-af-za:
	# make GDNAME=africa taginfo-af-za
	@echo " Start test  af-za :: South Africa     ::     mapped local port after finishing   127.0.0.1:11063"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-za	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-za /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-za

taginfo-af-zm:
	# make GDNAME=africa taginfo-af-zm
	@echo " Start test  af-zm :: Zambia     ::     mapped local port after finishing   127.0.0.1:11064"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-zm	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-zm /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-zm

taginfo-af-zw:
	# make GDNAME=africa taginfo-af-zw
	@echo " Start test  af-zw :: Zimbabwe     ::     mapped local port after finishing   127.0.0.1:11065"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-af-zw	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-af-zw /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-af-zw


# generated : 2019-12-29:15:08