# generated : 2019-12-29:16:02  // template : ./setup/template/Makefile.jinja2

CURRENT_UID:=$(shell echo $$(id -u):$$(id -g))
export CURRENT_UID

down:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose down

clean:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose rm -f -v


taginfo-sa-ar:
	# make GDNAME=south-america taginfo-sa-ar
	@echo " Start test  sa-ar :: Argentina     ::     mapped local port after finishing   127.0.0.1:26001"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-ar	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-ar /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-ar

taginfo-sa-bo:
	# make GDNAME=south-america taginfo-sa-bo
	@echo " Start test  sa-bo :: Bolivia     ::     mapped local port after finishing   127.0.0.1:26002"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-bo	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-bo /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-bo

taginfo-sa-br:
	# make GDNAME=brazil taginfo-sa-br
	@echo " Start test  sa-br :: Brazil     ::     mapped local port after finishing   127.0.0.1:26003"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-br	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-br /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-br

taginfo-sa-ck:
	# make GDNAME=south-america taginfo-sa-ck
	@echo " Start test  sa-ck :: Cook Islands     ::     mapped local port after finishing   127.0.0.1:26004"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-ck	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-ck /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-ck

taginfo-sa-cl:
	# make GDNAME=chile taginfo-sa-cl
	@echo " Start test  sa-cl :: Chile     ::     mapped local port after finishing   127.0.0.1:26005"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-cl	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-cl /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-cl

taginfo-sa-co:
	# make GDNAME=colombia taginfo-sa-co
	@echo " Start test  sa-co :: Colombia     ::     mapped local port after finishing   127.0.0.1:26006"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-co	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-co /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-co

taginfo-sa-ec:
	# make GDNAME=south-america taginfo-sa-ec
	@echo " Start test  sa-ec :: Ecuador     ::     mapped local port after finishing   127.0.0.1:26007"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-ec	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-ec /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-ec

taginfo-sa-fk:
	# make GDNAME=south-america taginfo-sa-fk
	@echo " Start test  sa-fk :: Falkland Islands     ::     mapped local port after finishing   127.0.0.1:26008"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-fk	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-fk /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-fk

taginfo-sa-fr-cp:
	# make GDNAME=south-america taginfo-sa-fr-cp
	@echo " Start test  sa-fr-cp :: Clipperton Island     ::     mapped local port after finishing   127.0.0.1:26009"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-fr-cp	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-fr-cp /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-fr-cp

taginfo-sa-fr-gf:
	# make GDNAME=south-america taginfo-sa-fr-gf
	@echo " Start test  sa-fr-gf :: French Guiana     ::     mapped local port after finishing   127.0.0.1:26011"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-fr-gf	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-fr-gf /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-fr-gf

taginfo-sa-fr-pf:
	# make GDNAME=south-america taginfo-sa-fr-pf
	@echo " Start test  sa-fr-pf :: French Polynesia     ::     mapped local port after finishing   127.0.0.1:26012"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-fr-pf	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-fr-pf /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-fr-pf

taginfo-sa-gs:
	# make GDNAME=south-america taginfo-sa-gs
	@echo " Start test  sa-gs :: South Georgia and the South Sandwich Islands     ::     mapped local port after finishing   127.0.0.1:26013"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-gs	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-gs /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-gs

taginfo-sa-gy:
	# make GDNAME=south-america taginfo-sa-gy
	@echo " Start test  sa-gy :: Guyana     ::     mapped local port after finishing   127.0.0.1:26014"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-gy	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-gy /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-gy

taginfo-sa-nl-aw:
	# make GDNAME=central-america taginfo-sa-nl-aw
	@echo " Start test  sa-nl-aw :: Aruba     ::     mapped local port after finishing   127.0.0.1:26015"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-nl-aw	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-nl-aw /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-nl-aw

taginfo-sa-nl-cw:
	# make GDNAME=central-america taginfo-sa-nl-cw
	@echo " Start test  sa-nl-cw :: Curacao     ::     mapped local port after finishing   127.0.0.1:26016"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-nl-cw	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-nl-cw /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-nl-cw

taginfo-sa-nu:
	# make GDNAME=south-america taginfo-sa-nu
	@echo " Start test  sa-nu :: Niue     ::     mapped local port after finishing   127.0.0.1:26017"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-nu	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-nu /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-nu

taginfo-sa-pe:
	# make GDNAME=south-america taginfo-sa-pe
	@echo " Start test  sa-pe :: Peru     ::     mapped local port after finishing   127.0.0.1:26018"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-pe	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-pe /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-pe

taginfo-sa-pn:
	# make GDNAME=south-america taginfo-sa-pn
	@echo " Start test  sa-pn :: Pitcairn Islands     ::     mapped local port after finishing   127.0.0.1:26019"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-pn	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-pn /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-pn

taginfo-sa-py:
	# make GDNAME=paraguay taginfo-sa-py
	@echo " Start test  sa-py :: Paraguay     ::     mapped local port after finishing   127.0.0.1:26020"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-py	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-py /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-py

taginfo-sa-sr:
	# make GDNAME=south-america taginfo-sa-sr
	@echo " Start test  sa-sr :: Suriname     ::     mapped local port after finishing   127.0.0.1:26021"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-sr	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-sr /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-sr

taginfo-sa-tk:
	# make GDNAME=south-america taginfo-sa-tk
	@echo " Start test  sa-tk :: Tokelau     ::     mapped local port after finishing   127.0.0.1:26022"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-tk	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-tk /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-tk

taginfo-sa-to:
	# make GDNAME=south-america taginfo-sa-to
	@echo " Start test  sa-to :: Tonga     ::     mapped local port after finishing   127.0.0.1:26023"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-to	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-to /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-to

taginfo-sa-us-as:
	# make GDNAME=south-america taginfo-sa-us-as
	@echo " Start test  sa-us-as :: American Samoa     ::     mapped local port after finishing   127.0.0.1:26024"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-us-as	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-us-as /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-us-as

taginfo-sa-us-um:
	# make GDNAME=south-america taginfo-sa-us-um
	@echo " Start test  sa-us-um :: United States of America (Minor Outlying Islands);Kingman Reef     ::     mapped local port after finishing   127.0.0.1:26026"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-us-um	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-us-um /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-us-um

taginfo-sa-uy:
	# make GDNAME=south-america taginfo-sa-uy
	@echo " Start test  sa-uy :: Uruguay     ::     mapped local port after finishing   127.0.0.1:26030"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-uy	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-uy /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-uy

taginfo-sa-ve:
	# make GDNAME=south-america taginfo-sa-ve
	@echo " Start test  sa-ve :: Venezuela     ::     mapped local port after finishing   127.0.0.1:26031"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-ve	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-ve /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-ve

taginfo-sa-ws:
	# make GDNAME=south-america taginfo-sa-ws
	@echo " Start test  sa-ws :: Samoa     ::     mapped local port after finishing   127.0.0.1:26032"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-sa-ws	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-sa-ws /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-sa-ws


# generated : 2019-12-29:16:02