# generated : 2019-12-29:14:52  // template : ./setup/template/Makefile.jinja2

CURRENT_UID:=$(shell echo $$(id -u):$$(id -g))
export CURRENT_UID

down:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose down

clean:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose rm -f -v


taginfo-ca-ag:
	# make GDNAME=central-america taginfo-ca-ag
	@echo " Start test  ca-ag :: Antigua and Barbuda     ::     mapped local port after finishing   127.0.0.1:18001"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-ag	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-ag /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-ag

taginfo-ca-ai:
	# make GDNAME=central-america taginfo-ca-ai
	@echo " Start test  ca-ai :: Anguilla     ::     mapped local port after finishing   127.0.0.1:18002"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-ai	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-ai /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-ai

taginfo-ca-bb:
	# make GDNAME=central-america taginfo-ca-bb
	@echo " Start test  ca-bb :: Barbados     ::     mapped local port after finishing   127.0.0.1:18003"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-bb	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-bb /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-bb

taginfo-ca-bq:
	# make GDNAME=central-america taginfo-ca-bq
	@echo " Start test  ca-bq :: Caribbean Netherlands     ::     mapped local port after finishing   127.0.0.1:18004"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-bq	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-bq /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-bq

taginfo-ca-bs:
	# make GDNAME=bahamas taginfo-ca-bs
	@echo " Start test  ca-bs :: The Bahamas     ::     mapped local port after finishing   127.0.0.1:18005"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-bs	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-bs /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-bs

taginfo-ca-bz:
	# make GDNAME=central-america taginfo-ca-bz
	@echo " Start test  ca-bz :: Belize     ::     mapped local port after finishing   127.0.0.1:18006"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-bz	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-bz /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-bz

taginfo-ca-cr:
	# make GDNAME=central-america taginfo-ca-cr
	@echo " Start test  ca-cr :: Costa Rica     ::     mapped local port after finishing   127.0.0.1:18007"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-cr	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-cr /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-cr

taginfo-ca-cu:
	# make GDNAME=central-america taginfo-ca-cu
	@echo " Start test  ca-cu :: Cuba     ::     mapped local port after finishing   127.0.0.1:18008"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-cu	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-cu /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-cu

taginfo-ca-dm:
	# make GDNAME=central-america taginfo-ca-dm
	@echo " Start test  ca-dm :: Dominica     ::     mapped local port after finishing   127.0.0.1:18009"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-dm	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-dm /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-dm

taginfo-ca-do:
	# make GDNAME=central-america taginfo-ca-do
	@echo " Start test  ca-do :: Dominican Republic     ::     mapped local port after finishing   127.0.0.1:18010"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-do	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-do /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-do

taginfo-ca-fr-bl:
	# make GDNAME=central-america taginfo-ca-fr-bl
	@echo " Start test  ca-fr-bl :: Saint Barthélemy     ::     mapped local port after finishing   127.0.0.1:18011"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-fr-bl	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-fr-bl /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-fr-bl

taginfo-ca-fr-mf:
	# make GDNAME=central-america taginfo-ca-fr-mf
	@echo " Start test  ca-fr-mf :: Saint Martin (France)     ::     mapped local port after finishing   127.0.0.1:18012"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-fr-mf	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-fr-mf /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-fr-mf

taginfo-ca-fr-mq:
	# make GDNAME=central-america taginfo-ca-fr-mq
	@echo " Start test  ca-fr-mq :: Martinique     ::     mapped local port after finishing   127.0.0.1:18013"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-fr-mq	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-fr-mq /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-fr-mq

taginfo-ca-gd:
	# make GDNAME=central-america taginfo-ca-gd
	@echo " Start test  ca-gd :: Grenada     ::     mapped local port after finishing   127.0.0.1:18014"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-gd	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-gd /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-gd

taginfo-ca-gp:
	# make GDNAME=central-america taginfo-ca-gp
	@echo " Start test  ca-gp :: Guadeloupe     ::     mapped local port after finishing   127.0.0.1:18015"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-gp	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-gp /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-gp

taginfo-ca-gt:
	# make GDNAME=central-america taginfo-ca-gt
	@echo " Start test  ca-gt :: Guatemala     ::     mapped local port after finishing   127.0.0.1:18016"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-gt	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-gt /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-gt

taginfo-ca-hn:
	# make GDNAME=central-america taginfo-ca-hn
	@echo " Start test  ca-hn :: Honduras     ::     mapped local port after finishing   127.0.0.1:18017"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-hn	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-hn /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-hn

taginfo-ca-ht:
	# make GDNAME=central-america taginfo-ca-ht
	@echo " Start test  ca-ht :: Haiti     ::     mapped local port after finishing   127.0.0.1:18018"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-ht	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-ht /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-ht

taginfo-ca-jm:
	# make GDNAME=jamaica taginfo-ca-jm
	@echo " Start test  ca-jm :: Jamaica     ::     mapped local port after finishing   127.0.0.1:18019"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-jm	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-jm /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-jm

taginfo-ca-kn:
	# make GDNAME=central-america taginfo-ca-kn
	@echo " Start test  ca-kn :: Saint Kitts and Nevis     ::     mapped local port after finishing   127.0.0.1:18020"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-kn	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-kn /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-kn

taginfo-ca-ky:
	# make GDNAME=central-america taginfo-ca-ky
	@echo " Start test  ca-ky :: Cayman Islands     ::     mapped local port after finishing   127.0.0.1:18021"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-ky	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-ky /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-ky

taginfo-ca-lc:
	# make GDNAME=central-america taginfo-ca-lc
	@echo " Start test  ca-lc :: Saint Lucia     ::     mapped local port after finishing   127.0.0.1:18022"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-lc	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-lc /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-lc

taginfo-ca-ms:
	# make GDNAME=central-america taginfo-ca-ms
	@echo " Start test  ca-ms :: Montserrat     ::     mapped local port after finishing   127.0.0.1:18023"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-ms	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-ms /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-ms

taginfo-ca-ni:
	# make GDNAME=central-america taginfo-ca-ni
	@echo " Start test  ca-ni :: Nicaragua     ::     mapped local port after finishing   127.0.0.1:18024"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-ni	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-ni /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-ni

taginfo-ca-nl-aw:
	# make GDNAME=central-america taginfo-ca-nl-aw
	@echo " Start test  ca-nl-aw :: Aruba     ::     mapped local port after finishing   127.0.0.1:18025"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-nl-aw	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-nl-aw /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-nl-aw

taginfo-ca-nl-cw:
	# make GDNAME=central-america taginfo-ca-nl-cw
	@echo " Start test  ca-nl-cw :: Curacao     ::     mapped local port after finishing   127.0.0.1:18026"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-nl-cw	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-nl-cw /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-nl-cw

taginfo-ca-nl-sx:
	# make GDNAME=central-america taginfo-ca-nl-sx
	@echo " Start test  ca-nl-sx :: Sint Maarten (Netherlands)     ::     mapped local port after finishing   127.0.0.1:18027"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-nl-sx	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-nl-sx /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-nl-sx

taginfo-ca-sv:
	# make GDNAME=central-america taginfo-ca-sv
	@echo " Start test  ca-sv :: El Salvador     ::     mapped local port after finishing   127.0.0.1:18028"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-sv	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-sv /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-sv

taginfo-ca-tc:
	# make GDNAME=central-america taginfo-ca-tc
	@echo " Start test  ca-tc :: Turks and Caicos Islands     ::     mapped local port after finishing   127.0.0.1:18029"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-tc	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-tc /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-tc

taginfo-ca-tt:
	# make GDNAME=central-america taginfo-ca-tt
	@echo " Start test  ca-tt :: Trinidad and Tobago     ::     mapped local port after finishing   127.0.0.1:18030"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-tt	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-tt /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-tt

taginfo-ca-vc:
	# make GDNAME=central-america taginfo-ca-vc
	@echo " Start test  ca-vc :: Saint Vincent and the Grenadines     ::     mapped local port after finishing   127.0.0.1:18031"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-vc	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-vc /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-vc

taginfo-ca-vg:
	# make GDNAME=central-america taginfo-ca-vg
	@echo " Start test  ca-vg :: British Virgin Islands     ::     mapped local port after finishing   127.0.0.1:18032"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ca-vg	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ca-vg /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ca-vg


# generated : 2019-12-29:14:52