# generated : 2019-12-29:15:25  // template : ./setup/template/Makefile.jinja2

CURRENT_UID:=$(shell echo $$(id -u):$$(id -g))
export CURRENT_UID

down:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose down

clean:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose rm -f -v


taginfo-as-ae:
	# make GDNAME=gcc-states taginfo-as-ae
	@echo " Start test  as-ae :: United Arab Emirates     ::     mapped local port after finishing   127.0.0.1:14001"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-ae	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-ae /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-ae

taginfo-as-af:
	# make GDNAME=asia taginfo-as-af
	@echo " Start test  as-af :: Afghanistan     ::     mapped local port after finishing   127.0.0.1:14002"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-af	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-af /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-af

taginfo-as-am:
	# make GDNAME=asia taginfo-as-am
	@echo " Start test  as-am :: Armenia     ::     mapped local port after finishing   127.0.0.1:14003"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-am	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-am /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-am

taginfo-as-az:
	# make GDNAME=asia taginfo-as-az
	@echo " Start test  as-az :: Azerbaijan     ::     mapped local port after finishing   127.0.0.1:14004"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-az	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-az /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-az

taginfo-as-bd:
	# make GDNAME=asia taginfo-as-bd
	@echo " Start test  as-bd :: Bangladesh     ::     mapped local port after finishing   127.0.0.1:14005"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-bd	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-bd /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-bd

taginfo-as-bh:
	# make GDNAME=gcc-states taginfo-as-bh
	@echo " Start test  as-bh :: Bahrain     ::     mapped local port after finishing   127.0.0.1:14006"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-bh	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-bh /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-bh

taginfo-as-bn:
	# make GDNAME=malaysia-singapore-brunei taginfo-as-bn
	@echo " Start test  as-bn :: Brunei     ::     mapped local port after finishing   127.0.0.1:14007"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-bn	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-bn /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-bn

taginfo-as-bt:
	# make GDNAME=asia taginfo-as-bt
	@echo " Start test  as-bt :: Bhutan     ::     mapped local port after finishing   127.0.0.1:14008"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-bt	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-bt /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-bt

taginfo-as-cn:
	# make GDNAME=asia taginfo-as-cn
	@echo " Start test  as-cn :: China     ::     mapped local port after finishing   127.0.0.1:14009"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-cn	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-cn /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-cn

taginfo-as-ge:
	# make GDNAME=europe taginfo-as-ge
	@echo " Start test  as-ge :: Georgia     ::     mapped local port after finishing   127.0.0.1:14010"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-ge	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-ge /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-ge

taginfo-as-id:
	# make GDNAME=asia taginfo-as-id
	@echo " Start test  as-id :: Indonesia     ::     mapped local port after finishing   127.0.0.1:14011"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-id	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-id /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-id

taginfo-as-il:
	# make GDNAME=asia taginfo-as-il
	@echo " Start test  as-il :: Israel     ::     mapped local port after finishing   127.0.0.1:14012"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-il	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-il /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-il

taginfo-as-in:
	# make GDNAME=asia taginfo-as-in
	@echo " Start test  as-in :: India     ::     mapped local port after finishing   127.0.0.1:14013"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-in	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-in /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-in

taginfo-as-io:
	# make GDNAME=asia taginfo-as-io
	@echo " Start test  as-io :: British Indian Ocean Territory     ::     mapped local port after finishing   127.0.0.1:14014"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-io	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-io /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-io

taginfo-as-iq:
	# make GDNAME=asia taginfo-as-iq
	@echo " Start test  as-iq :: Iraq     ::     mapped local port after finishing   127.0.0.1:14015"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-iq	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-iq /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-iq

taginfo-as-ir:
	# make GDNAME=asia taginfo-as-ir
	@echo " Start test  as-ir :: Iran     ::     mapped local port after finishing   127.0.0.1:14016"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-ir	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-ir /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-ir

taginfo-as-jo:
	# make GDNAME=asia taginfo-as-jo
	@echo " Start test  as-jo :: Jordan     ::     mapped local port after finishing   127.0.0.1:14017"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-jo	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-jo /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-jo

taginfo-as-jp:
	# make GDNAME=japan taginfo-as-jp
	@echo " Start test  as-jp :: Japan     ::     mapped local port after finishing   127.0.0.1:14018"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-jp	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-jp /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-jp

taginfo-as-kg:
	# make GDNAME=asia taginfo-as-kg
	@echo " Start test  as-kg :: Kyrgyzstan     ::     mapped local port after finishing   127.0.0.1:14019"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-kg	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-kg /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-kg

taginfo-as-kh:
	# make GDNAME=asia taginfo-as-kh
	@echo " Start test  as-kh :: Cambodia     ::     mapped local port after finishing   127.0.0.1:14020"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-kh	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-kh /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-kh

taginfo-as-kp:
	# make GDNAME=asia taginfo-as-kp
	@echo " Start test  as-kp :: North Korea     ::     mapped local port after finishing   127.0.0.1:14021"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-kp	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-kp /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-kp

taginfo-as-kr:
	# make GDNAME=asia taginfo-as-kr
	@echo " Start test  as-kr :: South Korea     ::     mapped local port after finishing   127.0.0.1:14022"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-kr	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-kr /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-kr

taginfo-as-kw:
	# make GDNAME=asia taginfo-as-kw
	@echo " Start test  as-kw :: Kuwait     ::     mapped local port after finishing   127.0.0.1:14023"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-kw	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-kw /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-kw

taginfo-as-kz:
	# make GDNAME=asia taginfo-as-kz
	@echo " Start test  as-kz :: Kazakhstan     ::     mapped local port after finishing   127.0.0.1:14024"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-kz	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-kz /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-kz

taginfo-as-la:
	# make GDNAME=asia taginfo-as-la
	@echo " Start test  as-la :: Laos     ::     mapped local port after finishing   127.0.0.1:14025"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-la	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-la /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-la

taginfo-as-lb:
	# make GDNAME=asia taginfo-as-lb
	@echo " Start test  as-lb :: Lebanon     ::     mapped local port after finishing   127.0.0.1:14026"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-lb	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-lb /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-lb

taginfo-as-lk:
	# make GDNAME=asia taginfo-as-lk
	@echo " Start test  as-lk :: Sri Lanka     ::     mapped local port after finishing   127.0.0.1:14027"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-lk	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-lk /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-lk

taginfo-as-mm:
	# make GDNAME=asia taginfo-as-mm
	@echo " Start test  as-mm :: Myanmar     ::     mapped local port after finishing   127.0.0.1:14028"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-mm	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-mm /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-mm

taginfo-as-mn:
	# make GDNAME=asia taginfo-as-mn
	@echo " Start test  as-mn :: Mongolia     ::     mapped local port after finishing   127.0.0.1:14029"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-mn	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-mn /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-mn

taginfo-as-mv:
	# make GDNAME=maldives taginfo-as-mv
	@echo " Start test  as-mv :: Maldives     ::     mapped local port after finishing   127.0.0.1:14030"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-mv	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-mv /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-mv

taginfo-as-my:
	# make GDNAME=asia taginfo-as-my
	@echo " Start test  as-my :: Malaysia     ::     mapped local port after finishing   127.0.0.1:14031"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-my	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-my /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-my

taginfo-as-np:
	# make GDNAME=asia taginfo-as-np
	@echo " Start test  as-np :: Nepal     ::     mapped local port after finishing   127.0.0.1:14032"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-np	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-np /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-np

taginfo-as-om:
	# make GDNAME=asia taginfo-as-om
	@echo " Start test  as-om :: Oman     ::     mapped local port after finishing   127.0.0.1:14033"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-om	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-om /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-om

taginfo-as-ph:
	# make GDNAME=asia taginfo-as-ph
	@echo " Start test  as-ph :: Philippines     ::     mapped local port after finishing   127.0.0.1:14034"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-ph	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-ph /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-ph

taginfo-as-pk:
	# make GDNAME=asia taginfo-as-pk
	@echo " Start test  as-pk :: Pakistan     ::     mapped local port after finishing   127.0.0.1:14035"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-pk	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-pk /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-pk

taginfo-as-qa:
	# make GDNAME=asia taginfo-as-qa
	@echo " Start test  as-qa :: Qatar     ::     mapped local port after finishing   127.0.0.1:14036"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-qa	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-qa /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-qa

taginfo-as-sa:
	# make GDNAME=asia taginfo-as-sa
	@echo " Start test  as-sa :: Saudi Arabia     ::     mapped local port after finishing   127.0.0.1:14037"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-sa	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-sa /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-sa

taginfo-as-sg:
	# make GDNAME=asia taginfo-as-sg
	@echo " Start test  as-sg :: Singapore     ::     mapped local port after finishing   127.0.0.1:14038"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-sg	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-sg /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-sg

taginfo-as-sy:
	# make GDNAME=asia taginfo-as-sy
	@echo " Start test  as-sy :: Syria     ::     mapped local port after finishing   127.0.0.1:14039"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-sy	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-sy /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-sy

taginfo-as-th:
	# make GDNAME=asia taginfo-as-th
	@echo " Start test  as-th :: Thailand     ::     mapped local port after finishing   127.0.0.1:14040"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-th	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-th /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-th

taginfo-as-tj:
	# make GDNAME=asia taginfo-as-tj
	@echo " Start test  as-tj :: Tajikistan     ::     mapped local port after finishing   127.0.0.1:14041"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-tj	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-tj /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-tj

taginfo-as-tl:
	# make GDNAME=indonesia taginfo-as-tl
	@echo " Start test  as-tl :: East Timor     ::     mapped local port after finishing   127.0.0.1:14042"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-tl	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-tl /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-tl

taginfo-as-tm:
	# make GDNAME=asia taginfo-as-tm
	@echo " Start test  as-tm :: Turkmenistan     ::     mapped local port after finishing   127.0.0.1:14043"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-tm	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-tm /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-tm

taginfo-as-tw:
	# make GDNAME=asia taginfo-as-tw
	@echo " Start test  as-tw :: Taiwan     ::     mapped local port after finishing   127.0.0.1:14044"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-tw	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-tw /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-tw

taginfo-as-uz:
	# make GDNAME=asia taginfo-as-uz
	@echo " Start test  as-uz :: Uzbekistan     ::     mapped local port after finishing   127.0.0.1:14045"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-uz	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-uz /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-uz

taginfo-as-vn:
	# make GDNAME=asia taginfo-as-vn
	@echo " Start test  as-vn :: Vietnam     ::     mapped local port after finishing   127.0.0.1:14046"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-vn	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-vn /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-vn

taginfo-as-ye:
	# make GDNAME=asia taginfo-as-ye
	@echo " Start test  as-ye :: Yemen     ::     mapped local port after finishing   127.0.0.1:14047"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-as-ye	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-as-ye /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-as-ye


# generated : 2019-12-29:15:25