# generated : 2019-12-29:15:33  // template : ./setup/template/Makefile.jinja2

CURRENT_UID:=$(shell echo $$(id -u):$$(id -g))
export CURRENT_UID

down:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose down

clean:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose rm -f -v


taginfo-ao-au:
	# make GDNAME=australia-oceania taginfo-ao-au
	@echo " Start test  ao-au :: Australia     ::     mapped local port after finishing   127.0.0.1:16001"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-au	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-au /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-au

taginfo-ao-cc:
	# make GDNAME=australia-oceania taginfo-ao-cc
	@echo " Start test  ao-cc :: Cocos (Keeling) Islands     ::     mapped local port after finishing   127.0.0.1:16002"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-cc	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-cc /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-cc

taginfo-ao-cx:
	# make GDNAME=australia-oceania taginfo-ao-cx
	@echo " Start test  ao-cx :: Christmas Island     ::     mapped local port after finishing   127.0.0.1:16003"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-cx	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-cx /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-cx

taginfo-ao-fj:
	# make GDNAME=australia-oceania taginfo-ao-fj
	@echo " Start test  ao-fj :: Fiji     ::     mapped local port after finishing   127.0.0.1:16004"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-fj	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-fj /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-fj

taginfo-ao-fm:
	# make GDNAME=australia-oceania taginfo-ao-fm
	@echo " Start test  ao-fm :: Federated States of Micronesia     ::     mapped local port after finishing   127.0.0.1:16005"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-fm	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-fm /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-fm

taginfo-ao-fr-nc:
	# make GDNAME=new-caledonia taginfo-ao-fr-nc
	@echo " Start test  ao-fr-nc :: New Caledonia     ::     mapped local port after finishing   127.0.0.1:16006"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-fr-nc	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-fr-nc /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-fr-nc

taginfo-ao-fr-tf:
	# make GDNAME=australia-oceania taginfo-ao-fr-tf
	@echo " Start test  ao-fr-tf :: French Southern and Antarctic Lands     ::     mapped local port after finishing   127.0.0.1:16007"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-fr-tf	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-fr-tf /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-fr-tf

taginfo-ao-hm:
	# make GDNAME=australia-oceania taginfo-ao-hm
	@echo " Start test  ao-hm :: Heard Island and McDonald Islands     ::     mapped local port after finishing   127.0.0.1:16008"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-hm	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-hm /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-hm

taginfo-ao-ki:
	# make GDNAME=australia-oceania taginfo-ao-ki
	@echo " Start test  ao-ki :: Kiribati     ::     mapped local port after finishing   127.0.0.1:16009"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-ki	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-ki /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-ki

taginfo-ao-mh:
	# make GDNAME=australia-oceania taginfo-ao-mh
	@echo " Start test  ao-mh :: Marshall Islands     ::     mapped local port after finishing   127.0.0.1:16010"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-mh	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-mh /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-mh

taginfo-ao-nf:
	# make GDNAME=australia taginfo-ao-nf
	@echo " Start test  ao-nf :: Norfolk Island     ::     mapped local port after finishing   127.0.0.1:16011"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-nf	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-nf /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-nf

taginfo-ao-nr:
	# make GDNAME=australia-oceania taginfo-ao-nr
	@echo " Start test  ao-nr :: Nauru     ::     mapped local port after finishing   127.0.0.1:16012"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-nr	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-nr /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-nr

taginfo-ao-nz:
	# make GDNAME=australia-oceania taginfo-ao-nz
	@echo " Start test  ao-nz :: New Zealand     ::     mapped local port after finishing   127.0.0.1:16013"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-nz	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-nz /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-nz

taginfo-ao-pg:
	# make GDNAME=papua-new-guinea taginfo-ao-pg
	@echo " Start test  ao-pg :: Papua New Guinea     ::     mapped local port after finishing   127.0.0.1:16014"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-pg	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-pg /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-pg

taginfo-ao-pw:
	# make GDNAME=australia-oceania taginfo-ao-pw
	@echo " Start test  ao-pw :: Palau     ::     mapped local port after finishing   127.0.0.1:16015"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-pw	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-pw /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-pw

taginfo-ao-sb:
	# make GDNAME=australia-oceania taginfo-ao-sb
	@echo " Start test  ao-sb :: Solomon Islands     ::     mapped local port after finishing   127.0.0.1:16016"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-sb	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-sb /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-sb

taginfo-ao-tv:
	# make GDNAME=australia-oceania taginfo-ao-tv
	@echo " Start test  ao-tv :: Tuvalu     ::     mapped local port after finishing   127.0.0.1:16017"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-tv	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-tv /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-tv

taginfo-ao-us-gu:
	# make GDNAME=australia-oceania taginfo-ao-us-gu
	@echo " Start test  ao-us-gu :: Guam     ::     mapped local port after finishing   127.0.0.1:16018"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-us-gu	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-us-gu /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-us-gu

taginfo-ao-us-mp:
	# make GDNAME=australia-oceania taginfo-ao-us-mp
	@echo " Start test  ao-us-mp :: Northern Mariana Islands     ::     mapped local port after finishing   127.0.0.1:16019"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-us-mp	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-us-mp /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-us-mp

taginfo-ao-us-um:
	# make GDNAME=australia-oceania taginfo-ao-us-um
	@echo " Start test  ao-us-um :: United States of America (Minor Outlying Islands);Wake Island (Disputed area USA-MARSHALL ISLANDS)     ::     mapped local port after finishing   127.0.0.1:16020"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-us-um	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-us-um /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-us-um

taginfo-ao-vu:
	# make GDNAME=australia-oceania taginfo-ao-vu
	@echo " Start test  ao-vu :: Vanuatu     ::     mapped local port after finishing   127.0.0.1:16021"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ao-vu	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ao-vu /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ao-vu


# generated : 2019-12-29:15:33